/*
 * Beneficiary API
 *
 * This is a simple Beneficiary API, where you can Create, Read, and Delete beneficiary
 *
 * API version: 1.0.0
 * Contact: mjangid@cynergybank.co.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	mj "go-server/go"
)

func main() {
	log.Printf("Server started")


	router := mj.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
