/*
 * Beneficiary API
 *
 * This is a simple Beneficiary API, where you can Create, Read, and Delete beneficiary
 *
 * API version: 1.0.0
 * Contact: mjangid@cynergybank.co.uk
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"//",
		Index,
	},

	Route{
		"CreateBeneficiary",
		strings.ToUpper("Post"),
		"//beneficiary",
		CreateBeneficiary,
	},

	Route{
		"DeleteBeneficiaryById",
		strings.ToUpper("Delete"),
		"//{beneficiaryId}",
		DeleteBeneficiaryById,
	},

	Route{
		"GetBeneficiary",
		strings.ToUpper("Get"),
		"//beneficiary",
		GetBeneficiary,
	},

	Route{
		"GetBeneficiaryById",
		strings.ToUpper("Get"),
		"//{beneficiaryId}",
		GetBeneficiaryById,
	},

	Route{
		"PatchBeneficiary",
		strings.ToUpper("Patch"),
		"//{beneficiaryId}",
		PatchBeneficiary,
	},

	Route{
		"PutBeneficiary",
		strings.ToUpper("Put"),
		"//{beneficiaryId}",
		PutBeneficiary,
	},
}
